### PR TITLE
Update dockerfile

### PR DESCRIPTION
**Pull request by devopseasylearning**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

> Detailed description here

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

> Links to Pivotal Tracker stories, JIRA tickets or other pull requests here

https://devopseasylearning.atlassian.net/browse/S02-158

> Describe any security impact this change may have

### CODE REVIEW

**Review by Bouba2021 — APPROVED** [review]
Good to go

**Review by igor581 — APPROVED** [review]
Look good

**Review by Anipal1 — APPROVED** [review]
It looks good

**Review by Galiomid — COMMENTED** [review]
approved

**Comment by fjen53** [comment]
good

**Review by YvanNys — APPROVED** [review]

**Comment by alfred030** [comment]
Exactly

**Pull request merged**
