### PR TITLE
S02-158. Cedric Update Dockerfile on Dev pipeline

### PR DESCRIPTION
**Pull request by CedricKen**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

Update Dockerfile

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

S02-158

## Security considerations

None

### CODE REVIEW

**Review by marabiocho — APPROVED** [review]
good job cedirc

**Review by Amy2900 — APPROVED** [review]

**Review by fjen53 — APPROVED** [review]

**Comment by fjen53** [comment]
good job

**Review by Adelanoumbo — COMMENTED** [review]
Good Job as usual :)

**Review by duclair3006 — APPROVED** [review]
good sir

**Review by ousmane777 — COMMENTED** [review]
nice job ..

**Comment by Maguilene** [comment]
just verified

**Pull request closed without merging**
