### PR TITLE
S02158. Amy- Update Dockerfile on Dev pipeline

### PR DESCRIPTION
**Pull request by Amy2900**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change
Update Dockerfile on Dev pipeline

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

S02158

## Security considerations

none

### CODE REVIEW

**Review by ousmane777 — APPROVED** [review]
you did a great job

**Review by Adelanoumbo — COMMENTED** [review]
Good Job Amy

**Comment by devopseasylearning** [comment]
good job

**Comment by RKemvou** [comment]
good job Amy

**Comment by Maguilene** [comment]
Just Checked

**Pull request closed without merging**
