### PR TITLE
S2-171. Eric update file

### PR DESCRIPTION
**Pull request by devopseasylearning**
updated Dockerfile with new enties

# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

Eric update file

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

S2-171.

## Security considerations

None

### CODE REVIEW

**Comment by CedricKen** [comment]
PR approuved. Green light to merge the code to pre-prod

**Review by alfred030 — APPROVED** [review]
DevOps

**Review by patdady — APPROVED** [review]

**Review by Bouba2021 — APPROVED** [review]
La mort mortuaire

**Review by CedricKen — APPROVED** [review]

**Review by barby202 — COMMENTED** [review]
reviewed!

**Review by Pierreta70 — APPROVED** [review]

**Comment by alfred030** [comment]
good job team

**Pull request merged**
