### PR TITLE
igor update file

### PR DESCRIPTION
**Pull request by igor581**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

> Detailed description here

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

> Links to Pivotal Tracker stories, JIRA tickets or other pull requests here

## Security considerations

> Describe any security impact this change may have

### CODE REVIEW

**Review by linsay1999 — CHANGES_REQUESTED** [review]
Add more lines in your file

**Review by linsay1999 — CHANGES_REQUESTED** [review]
still missing the additional files requested

**Review by willyaldes — CHANGES_REQUESTED** [review]
Looking good. Can you add a command that can display your current working directory?

**Comment by igor581** [comment]
ok guys thamks

**Review by linsay1999 — APPROVED** [review]
good now.

**Review by lucydaniel — APPROVED** [review]
Looks good, Igor you are there

**Review by Anipal1 — APPROVED** [review]
good

**Pull request closed without merging**
