### PR TITLE
S02158. Ousmane  Update Dockerfile on Dev pipeline

### PR DESCRIPTION
**Pull request by ousmane777**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

Update Dockerfile on Dev pipeline

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

S02158.

## Security considerations

none

### CODE REVIEW

**Review by Amy2900 — APPROVED** [review]

**Review by duclair3006 — COMMENTED** [review]
Mr ousmane everything looking good

**Review by marabiocho — COMMENTED** [review]
good job ousmane

**Review by CedricKen — APPROVED** [review]
Good job for updating the base image

**Comment by devopseasylearning** [comment]
good

**Pull request merged**
