### PR TITLE
Hop it works now

### PR DESCRIPTION
**Pull request by arnaudine1**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

> Detailed description here

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

> Links to Pivotal Tracker stories, JIRA tickets or other pull requests here

## Security considerations

> Describe any security impact this change may have

### CODE REVIEW

**Comment by Amy2900** [comment]
good job

**Review by Amy2900 — APPROVED** [review]

**Review by agueno — APPROVED** [review]
Good arnaude

**Review by CedricKen — COMMENTED** [review]
Will you tell me the description of you PR, and what changes you wantto implement ?
What is the ticket number you wanna resolve with this PR?

**Comment by arnaudine1** [comment]
Thanks guys

**Pull request merged**
