### PR TITLE
S02-233 igor training

### PR DESCRIPTION
**Pull request by igor581**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

> Detailed description here

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

> Links to Pivotal Tracker stories, JIRA tickets or other pull requests here

## Security considerations

> Describe any security impact this change may have

### CODE REVIEW

**Review by alfred030 — CHANGES_REQUESTED** [review]
Hi Igor, did you add all commands

**Comment by igor581** [comment]
yes i do

**Review by alfred030 — APPROVED** [review]

**Review by alfred030 — APPROVED** [review]
okay

**Comment by alfred030** [comment]
good to go

**Comment by igor581** [comment]
thank you

**Pull request merged**
