### PR TITLE
S02 198 igor update-dockerfile

### PR DESCRIPTION
**Pull request by igor581**
# WELCOME TO DEVOPS-EASY-LEARNING PULL REQUEST SYSTEM 
# Description of the change

> Detailed description here

## Checks and balances

- [ ] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

> Links to Pivotal Tracker stories, JIRA tickets or other pull requests here

## Security considerations

> Describe any security impact this change may have

### CODE REVIEW

**Review by linsay1999 — APPROVED** [review]
good job

**Review by Anipal1 — COMMENTED** [review]
kep pushing

**Comment by Anipal1** [comment]
you are almost there brother

**Review by Anipal1 — COMMENTED** [review]
kep pushing

**Review by jwandji — COMMENTED** [review]
looks good, but needs more clarification

**Pull request merged**
